services:
  browser-dashboard:
    image: node:22-bookworm-slim
    container_name: browser-dashboard
    working_dir: /app

    volumes:
      - .:/app                                      #Working app Directory
      - /DATA/AppData:/app/data/appData             #Path to where your docker containers are stored
      - /var/lib/casaos/apps/:/app/data/zimaAppData  #Optional secondary path to ZimaOS Apps

    ports:
      - "8085:3000"

    command: sh -c "npm install && npm run dev"

    environment:
      - NODE_ENV=development

    restart: unless-stopped